enyo.depends(
	"adddocumentpopup.js",
    "addpaymentpopup.js",
    "migratesubscriptionspanel.js",
    "assignpaymentpopup.js",
    "subscriptionfiltersettingspopup.js",
    "issuerlistpanel.js",
    "subscriberdetailpanel.js",
    "dashboardpanel.js",
    "closeplacementpanel.js",
    "csvexportpanel.js",
    "placementinfopanel.js",
    "issuerview.js",
    "addrefundpopup.js",
    "correctentrypopup.js",
    "duplicatewarnpopup.js"
);
